name = "mari8x"
compatibility_date = "2024-01-01"

[env.production]
name = "mari8x"
route = "mari8x.com/*"

[build]
command = "npm install && npx vite build"
cwd = ""
watch_dir = "src"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.html"

[[env.production.routes]]
pattern = "mari8x.com/*"
zone_name = "mari8x.com"
